package cyber;

import dbConnect.dbconnect;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import net.proteanit.sql.DbUtils;

public class displayCabin extends javax.swing.JPanel {

    Connection con=null;
    JScrollPane sp;
    DefaultTableModel dtm;
    
    public displayCabin() {
        initComponents();
        setValue();
    }
    public void setValue(){
    
        con=dbconnect.getDBConnection();
        int noofrows=0;
        try{
        
            Statement st=con.createStatement();
            String sql="select * from tbl_cabin";
            ResultSet rs=st.executeQuery(sql);
            rs.last();
            noofrows=rs.getRow();
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
            
         }
        
        String[] cols={"ID","Cabin","Status"};
        dtm=new DefaultTableModel(cols,noofrows);
        jTable1.setModel(dtm);
        
        try{
        
            Statement st1=con.createStatement();
            String sql1="select * from tbl_cabin";
            ResultSet rs1=st1.executeQuery(sql1);
            int x=0;
            
            while(rs1.next()){
            
                jTable1.setValueAt(rs1.getString(1),x,0);
                jTable1.setValueAt(rs1.getString(2),x,1);
                jTable1.setValueAt(rs1.getString(3),x,2);
                x++;
                
            }
        }catch(Exception ex){
        
            JOptionPane.showMessageDialog(null, ex);
        }
        
        TableColumnModel col=jTable1.getColumnModel();
        TableColumn c=col.getColumn(0);
            c.setMaxWidth(0);
            c.setMinWidth(0);
            c.setPreferredWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Display Cabin"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "S.N", "Cabin", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jLabel1.setText("Search");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Exit_delete_close_remove_door_logout_out.png"))); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButton2)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean isrowselected = jTable1.getSelectedRowCount() >= 0;
            
            if(isrowselected==true){
           
                int selectedRow = jTable1.getSelectedRow();
                System.out.println(selectedRow);
                Object c_id= jTable1.getValueAt(selectedRow, 0);
                int confirmdelete = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete?", "Confirm Delete",JOptionPane.YES_NO_OPTION);
            
                if(confirmdelete==0){
                    if(selectedRow>-1){
                            dtm.removeRow(selectedRow);
                            String sql="DELETE FROM tbl_cabin WHERE c_id="+c_id;
                            try {
                                Statement st=con.createStatement();
                                st.execute(sql);
                            } catch (Exception e) {
                                System.out.println("Data Not Deleted");
                            }
                    }
                }else{
                    

                }
            }else{
                JOptionPane.showConfirmDialog(this, "Please select a record to delete!!!", "Alert",JOptionPane.PLAIN_MESSAGE);

                
            }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased

       jTable1.repaint();
       try{
       
          Statement st=con.createStatement();
          String sql="select c_id ,title , status from tbl_cabin where title LIKE '"+jTextField1.getText()+"%'";
          ResultSet rs=st.executeQuery(sql);
          jTable1.setModel(DbUtils.resultSetToTableModel(rs));
       }catch(Exception e){
       
           System.out.println("eroor");
       }
       TableColumnModel col=jTable1.getColumnModel();
        TableColumn c=col.getColumn(0);
            c.setMaxWidth(0);
            c.setMinWidth(0);
            c.setPreferredWidth(0);
       
    }//GEN-LAST:event_jTextField1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
