package cyber;

import dbConnect.dbconnect;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

public class displayTariff extends javax.swing.JPanel {

   Connection con=null;
   JScrollPane sp;
   DefaultTableModel dtm;
   
    public displayTariff() {
        initComponents();
        con=dbconnect.getDBConnection();
        setValue();
    }

    public void setValue(){
    
        int noofrows=0;
        try{
        
            Statement st=con.createStatement();
            String sql="select * from tbl_tariff";
            ResultSet rs=st.executeQuery(sql);
            rs.last();
            noofrows=rs.getRow();
            
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Data not inserted");
    }
        String[] cols={"ID","Name","Amount","Registration Fee"};
        dtm=new DefaultTableModel(cols,noofrows);
        jTable1.setModel(dtm);
        
        try{
        
            Statement st1=con.createStatement();
            String sql1="select * from tbl_tariff";
            ResultSet rs1=st1.executeQuery(sql1);
            int x=0;
            while(rs1.next()){
            
                jTable1.setValueAt(rs1.getString(1),x,0);
                jTable1.setValueAt(rs1.getString(2),x,1);
                jTable1.setValueAt(rs1.getString(3),x,2);
                jTable1.setValueAt(rs1.getString(4),x,3);
                x++;
            }
        }catch(Exception e){
        
            JOptionPane.showMessageDialog(null, e);
        }
        TableColumnModel col=jTable1.getColumnModel();
        TableColumn c=col.getColumn(0);
        c.setMinWidth(0);
        c.setMaxWidth(0);
        c.setPreferredWidth(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Display Tariff", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Amount", "Registration Fee"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/07_plus-128.png"))); // NOI18N
        jLabel1.setText("Add");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/flat_seo2-32-128.png"))); // NOI18N
        jLabel2.setText("Edit");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel-128.png"))); // NOI18N
        jLabel3.setText("Delete");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addContainerGap(216, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        mainFrame.addContentPanel(new addTariff());
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        boolean isrowselected=jTable1.getSelectedRowCount()>0;
        if(isrowselected==true){
        
            int selectedRow=jTable1.getSelectedRow();
            Object t_id=jTable1.getValueAt(selectedRow, 0);
            mainFrame.addContentPanel(new editTariff(t_id));
        }else{
        
            JOptionPane.showConfirmDialog(this,"Please select a record to edit!!! ","Alert",JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
            
        boolean isrowselected=jTable1.getSelectedRow()>=0;
           if(isrowselected==true){
           int selectedRow=jTable1.getSelectedRow();
          // System.out.println(selectedRow);
           Object t_id=jTable1.getValueAt(selectedRow, 0);
           int confirmdelete=JOptionPane.showConfirmDialog(this,"Are you sure you want to delete?","Alert",JOptionPane.YES_NO_OPTION);
           
           if(confirmdelete==0){
           
               if(selectedRow>-1){
               
                   dtm.removeRow(selectedRow);
                   String sql="DELETE FROM tbl_tariff WHERE t_id="+t_id;
                   try{
                   
                       Statement st=con.createStatement();
                       st.execute(sql);
                   }catch(Exception ex){
                   
                       System.out.println(ex);
                   }
               }
           }
       }else{
       
           JOptionPane.showConfirmDialog(this,"Please select a record to delete!!!","Alert",JOptionPane.PLAIN_MESSAGE);
       }
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
